/** Wortliste für den Passwort-Generator (US-12).
 *
 *  Genau 1024 Wörter (2^10). Die Zahl ist nicht beliebig:
 *  - Entropieaussage: 4 Wörter × 10 Bit = 40 Bit, plus ~6,5 Bit aus den Ziffern
 *  - Modulo-Bias-Freiheit in generatePassword(): 2^32 muss glatt durch die
 *    Listenlänge teilbar sein
 *
 *  Auswahlkriterien:
 *  - 4–7 Zeichen (vorlesbar, tippbar)
 *  - nur a–z: keine Umlaute, kein ß (Handy-Layout, siehe auch US-08/B-01).
 *    Auch keine Wörter, deren korrekte Schreibweise einen Umlaut hätte —
 *    beim Vorlesen sagt man "Hütte", getippt würde "hutte".
 *  - keine Homophone: Rad/Rat, Meer/mehr, Lied/Lid, Seite/Saite
 *  - keine am Telefon verwechselbaren Paare: Nagel/Nadel, Katze/Tatze
 *  - keine anstößigen oder wertenden Begriffe (das Passwort wird vorgelesen)
 *  - nur konkrete Substantive, keine Abstrakta
 *
 *  Die Tests in wordlist.test.ts prüfen diese Eigenschaften hart. Wird die
 *  Liste geändert, muss die Länge exakt 1024 bleiben — sonst sind weder die
 *  Entropieaussage noch die Bias-Freiheit gültig.
 */
export const WORDS = [
  "adler", "affe", "akte", "alarm", "album", "ampel", "amsel", "ananas",
  "anker", "anorak", "antenne", "apfel", "april", "arche", "arena", "armband",
  "asche", "atlas", "auge", "august", "auster", "auto", "bach", "backe",
  "bagger", "bahn", "balken", "ball", "ballade", "ballon", "bambus", "band",
  "banjo", "bank", "bart", "basar", "basis", "bauer", "baum", "becher",
  "becken", "beere", "bein", "berg", "bericht", "besen", "besuch", "beton",
  "beutel", "bibel", "biber", "biene", "bier", "bild", "billard", "binde",
  "birke", "biskuit", "bison", "bistro", "blatt", "blech", "blei", "blende",
  "blitz", "block", "bluse", "boden", "bohne", "bohrer", "boiler", "boje",
  "bolzen", "bonbon", "boot", "bord", "borke", "brand", "brei", "brett",
  "brikett", "brille", "bronze", "brosche", "bruch", "brunnen", "buch", "buchse",
  "bucht", "buckel", "bude", "buffet", "bund", "bunker", "burg", "busch",
  "camp", "cello", "chef", "chip", "chor", "clown", "comic", "couch",
  "creme", "dach", "damm", "dampf", "dattel", "datum", "daumen", "degen",
  "delfin", "delta", "denkmal", "diamant", "diele", "diesel", "ding", "diplom",
  "distel", "docht", "dock", "doktor", "domino", "donner", "doppel", "dose",
  "drache", "draht", "drama", "dreieck", "dressur", "drossel", "druck", "duft",
  "dunst", "dusche", "duschen", "ebene", "ecke", "efeu", "eiche", "eichel",
  "eimer", "eisen", "elch", "elefant", "elster", "email", "emblem", "ende",
  "engel", "enkel", "epoche", "erbse", "erde", "erle", "ernte", "esel",
  "espe", "essig", "etage", "eule", "fabrik", "faden", "fagott", "fahne",
  "fahrer", "falke", "falle", "falte", "familie", "fanfare", "farbe", "farn",
  "fass", "faust", "feder", "feige", "feile", "feld", "felge", "fell",
  "fenster", "ferien", "ferkel", "ferse", "fest", "fett", "feuer", "fibel",
  "fichte", "figur", "film", "filter", "filz", "finger", "fisch", "flagge",
  "flamme", "flanke", "flasche", "flaum", "fleck", "fleisch", "fliege", "fliese",
  "flosse", "flug", "folie", "forelle", "form", "forst", "foto", "frack",
  "frage", "franse", "frau", "frisur", "frosch", "frost", "frucht", "fuchs",
  "funke", "futter", "gabel", "galerie", "galopp", "gans", "garage", "garten",
  "gasse", "gast", "gaumen", "gebet", "gebiet", "geblut", "geburt", "gedicht",
  "gehalt", "geige", "geist", "geld", "gelenk", "gericht", "geruch", "gestalt",
  "gewicht", "gewinn", "giebel", "gipfel", "gips", "gitarre", "gitter", "glanz",
  "glas", "glocke", "gnade", "gold", "gondel", "gorilla", "grab", "graben",
  "grad", "gramm", "granit", "gras", "grenze", "griff", "grille", "grotte",
  "grube", "grund", "gummi", "gurke", "gurt", "guss", "haar", "hacke",
  "hafen", "haft", "hagel", "hahn", "haken", "halle", "halm", "halt",
  "hammel", "hammer", "hamster", "hand", "handel", "handy", "hanf", "hang",
  "harfe", "harz", "hase", "haube", "hauch", "haupt", "haus", "haut",
  "hebel", "hecke", "heft", "heide", "heizung", "held", "helm", "hemd",
  "henne", "herbst", "herd", "herr", "hilfe", "himmel", "hirn", "hirsch",
  "hitze", "hobel", "hocke", "holz", "honig", "hopfen", "horde", "horn",
  "hose", "huhn", "hummel", "hummer", "humor", "hund", "igel", "iglu",
  "imker", "insekt", "insel", "jacke", "jager", "jahr", "jasmin", "jubel",
  "jucken", "jugend", "juli", "juni", "kabine", "kachel", "kader", "kaese",
  "kaffee", "kafig", "kaiser", "kajak", "kaktus", "kalb", "kamel", "kamera",
  "kamin", "kammer", "kampf", "kanal", "kanne", "kanu", "kapelle", "kappe",
  "karaffe", "kasten", "kater", "katze", "kauf", "kegel", "kehle", "keil",
  "keim", "keks", "kelle", "keller", "kerbe", "kern", "kerze", "kies",
  "kind", "kinn", "kino", "kiosk", "kirche", "kirsche", "kittel", "klammer",
  "klang", "klappe", "klasse", "klaue", "klavier", "kleid", "kleie", "klima",
  "klinge", "klippe", "kloster", "klotz", "klub", "knall", "knebel", "knecht",
  "knie", "knochen", "knopf", "knoten", "kobold", "koch", "koffer", "kohl",
  "koje", "kolben", "kolibri", "komet", "kompass", "konsul", "kopf", "kopie",
  "korb", "kosten", "kraft", "kragen", "kralle", "kran", "kranich", "kraut",
  "krebs", "kreide", "kreuz", "krippe", "krokus", "krone", "kruste", "kuchen",
  "kugel", "kulisse", "kunde", "kunst", "kupfer", "kuppel", "kurbel", "kurs",
  "kurve", "kuss", "kuste", "labor", "lachs", "laden", "lage", "lagune",
  "lamm", "land", "lanze", "lappen", "lasso", "laster", "laterne", "latte",
  "laub", "lauch", "laune", "laute", "lawine", "leber", "leder", "leer",
  "lehm", "lehne", "lehrer", "leib", "leine", "leiter", "lenker", "lerche",
  "lexikon", "libelle", "licht", "lilie", "limone", "linde", "linie", "linse",
  "lippe", "liste", "loch", "locke", "logik", "lohn", "lokal", "lorbeer",
  "lotse", "luchs", "luft", "luke", "lunge", "lust", "luxus", "magen",
  "magnet", "mahl", "mais", "makler", "malz", "mandel", "mange", "mann",
  "mantel", "mappe", "marder", "marke", "markt", "marmor", "marsch", "masse",
  "mast", "matrose", "matte", "mauer", "meer", "mehl", "meise", "meister",
  "menge", "mensch", "messe", "messer", "metall", "meter", "methode", "metzger",
  "miete", "milch", "minute", "mispel", "mitte", "mittel", "mode", "model",
  "modem", "moment", "monat", "mond", "moor", "moos", "mops", "morgen",
  "mosaik", "most", "motiv", "motte", "mund", "muschel", "muster", "nabel",
  "nacht", "nacken", "nadel", "nahrung", "name", "natur", "neffe", "nelke",
  "nerv", "nest", "neuling", "nickel", "niere", "niete", "nische", "niveau",
  "norden", "notiz", "nudel", "nuss", "oase", "obst", "ochse", "ofen",
  "oktober", "onkel", "oper", "orange", "orden", "organ", "orgel", "osten",
  "otter", "paar", "palast", "palme", "panda", "panne", "panther", "papagei",
  "papier", "paprika", "park", "parkett", "partie", "partner", "pass", "paste",
  "pause", "pedal", "pelz", "pendel", "pension", "person", "pfad", "pfanne",
  "pfau", "pfeffer", "pfeil", "pferd", "pflanze", "pflaume", "pforte", "pfosten",
  "pfote", "pfund", "phase", "pilger", "pille", "pilot", "pinsel", "pirat",
  "piste", "plakat", "plan", "planet", "platte", "platz", "plombe", "polster",
  "pony", "portal", "porto", "post", "pracht", "praline", "preis", "presse",
  "prinz", "prisma", "profil", "projekt", "prozent", "prufung", "pudel", "puder",
  "pulli", "puls", "pulver", "pumpe", "punkt", "puppe", "qualle", "quark",
  "quelle", "quirl", "quote", "rabe", "rachen", "rahmen", "rakete", "ralley",
  "rampe", "rand", "rasen", "rast", "ratte", "raub", "raum", "raupe",
  "rebe", "rechen", "recht", "rede", "regal", "regel", "regen", "reich",
  "reifen", "reihe", "reim", "reis", "rekord", "rennen", "rente", "rest",
  "revier", "rezept", "richter", "riegel", "riese", "rind", "rinne", "riss",
  "robbe", "robe", "rock", "roggen", "rolle", "roller", "roman", "rosine",
  "rost", "rotor", "route", "rubel", "rubin", "rucken", "ruder", "ruine",
  "runde", "rune", "rute", "saal", "saat", "sache", "sack", "sage",
  "sahne", "saison", "salat", "salbe", "salon", "same", "satz", "schacht",
  "schaf", "schall", "schar", "schatz", "schaum", "scheibe", "schein", "scherz",
  "scheune", "schicht", "schiene", "schiff", "schilf", "schirm", "schlaf", "schlag",
  "schlamm", "schloss", "schluss", "schmalz", "schmied", "schmuck", "schnee", "schnitt",
  "schnur", "scholle", "schoss", "schrank", "schrei", "schrift", "schritt", "schuh",
  "schule", "schuppe", "schuss", "schutz", "schwamm", "schwan", "schwanz", "schwung",
  "segel", "sehne", "seide", "seife", "seil", "sekunde", "senf", "sense",
  "serie", "sessel", "sicht", "sieb", "siedler", "siegel", "silo", "sims",
  "sirup", "sitte", "sitz", "skala", "skizze", "smaragd", "socke", "sohle",
  "sohn", "soldat", "sommer", "sonde", "sorge", "sorte", "sosse", "spalt",
  "span", "spargel", "sparte", "spaten", "spatz", "specht", "speck", "speiche",
  "speise", "spiegel", "spiess", "spinat", "spinne", "spirale", "spitze", "spore",
  "spray", "spross", "spruch", "sprung", "staat", "stab", "stachel", "stadt",
  "stahl", "stamm", "stand", "stapel", "star", "stark", "station", "statue",
  "staub", "steg", "stein", "stelle", "stempel", "steuer", "stich", "stiefel",
  "stier", "stift", "stil", "stimme", "stirn", "stock", "storch", "stoss",
  "strand", "strasse", "strauch", "strecke", "strich", "strick", "strom", "strudel",
  "strumpf", "stube", "stufe", "stuhl", "stunde", "sturm", "sturz", "stute",
  "sumpf", "suppe", "tabelle", "tablett", "tafel", "takt", "talent", "tank",
  "tante", "tanz", "tapete", "tarif", "tasche", "taste", "tausch", "taxi",
  "technik", "teich", "teil", "telefon", "tempel", "tempo", "tennis", "teppich",
  "termin", "test", "text", "theater", "thema", "thron", "tier", "tiger",
  "tinte", "tisch", "toast", "tochter", "tonne", "topf", "torte", "tour",
  "trab", "trafo", "trance", "transit", "traum", "treffen", "treppe", "tresor",
  "tribune", "trick", "trikot", "trinken", "tritt", "tropfen", "trost", "trupp",
  "tube", "tuch", "tunnel", "turban", "turnier", "ufer", "umweg", "union",
  "urlaub", "ursache", "vase", "ventil", "verlag", "vers", "vertrag", "vieh",
  "viertel", "villa", "violine", "virus", "vitamin", "vogel", "volk", "vorrat",
  "vorteil", "waage", "wachtel", "waffel", "wagen", "wahl", "wald", "walnuss",
  "walze", "wange", "ware", "wasser", "watte", "weber", "wechsel", "wehr",
  "weide", "weizen", "welt", "wende", "werbung", "werft", "werk", "wespe",
  "weste", "westen", "wiege", "wild", "wille", "wimper", "winkel", "winter",
  "wipfel", "wirbel", "wolf", "wolle", "wort", "wrack", "wunder", "wunsch",
  "wurf", "wurst", "wurzel", "zapfen", "zaun", "zebra", "zehe", "zeichen",
  "zeile", "zelt", "zement", "zentner", "zettel", "zeug", "ziege", "ziel",
  "ziffer", "zimt", "zinke", "zinn", "zins", "zipfel", "zirkel", "zirkus",
  "zitrone", "zoll", "zone", "zucker", "zunge", "zwerg", "zwiebel", "zwirn",
] as const;
